### ISSUE TITLE
dice so nice incompatibility

### ISSUE THREAD

**Issue by n0q** [n0q/hackmaster5e-fvtt#69]
Dice so Nice 3.4.0 occasionally breaks, throwing up an error when penetrating on a die roll.

**Steps to reproduce**
1. `/roll 1d4p` until the die finally penetrates.
2. Wait for dice to finish dropping.

Sometimes (but not every time) the following error will come up:
```
DiceBox.js:524 Uncaught TypeError: Cannot read property '0' of undefined
    at DiceBox.swapDiceFace (DiceBox.js:524)
    at DiceBox.rollDice (DiceBox.js:999)
    at DiceBox.start_throw (DiceBox.js:904)
    at main.js:860
    at main.js:722
```
Not yet sure if this is a DSN bug or a hackmaster dice code bug. Keeping this issue open as a reminder.

**Comment by n0q** [comment]
Confirmed I am only able to reproduce this behavior with the 'p' modifier. 'x' does not seem to do this.

**Comment by derg4** [comment]
This is probably caused by the hacky way the penetration code sets the dice results... When a "1" is rolled on a penetrating die, we tell foundry we rolled a "0" on that die, which works normally but I think the Dice So Nice code is trying to find the "0" face on the die (which doesn't exist) and make it face up, or something like that.

Maybe there's another way to get the dice results to work out correctly, or maybe it's possible to write some compatibility code somehow.

**Comment by n0q** [comment]
You might not need to alter your dice code for this. dsn offers quite a lot of machinery for driving die rolls manually. We could disable automatic 3drolls and manually tell dsn what to display.

**Comment by n0q** [comment]
This is fixed. DSN makes a deep copy of the roll structure for display purposes, so I'm just catching it in a hook and putting back the +1.

**Comment by n0q** [comment]
Original solution wasn't enough. It would crash on any DieTerm without a result, like Operations. Worse, PoolTerms encapsulate multiple DieTerms on their own. No longer assuming a results member, and drill down into Pools as needed (or until we hit a recursion limit).
